### ISSUE TITLE
Windows py3.5.2 hello.min.js fails to be created. FileNotFoundError

### ISSUE THREAD

**Issue by nueverest** [JdeH/Transcrypt#109]
I'm testing Transcrypt on Windows. The hello demo works with the non-minified JS that is generated, but `hello.min.js` fails to be created. 

Console output.
```
(transcrypt_hello_virtualenv) C:\Users\username\PycharmProjects\transcrypt_hello>python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

(transcrypt_hello_virtualenv) C:\Users\username\PycharmProjects\transcrypt_hello>python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

(transcrypt_hello_virtualenv) C:\Users\username\PycharmProjects\transcrypt_hello>pip freeze
Transcrypt==3.5.217

(transcrypt_hello_virtualenv) C:\Users\username\PycharmProjects\transcrypt_hello>transcrypt hello.py
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.5.217
Copyright (C) Geatec Engineering. License: Apache 2.0

Saving result in: C:/Users/username/PycharmProjects/transcrypt_hello/__javascript__/hello.js
Saving minified result in: C:/Users/username/PycharmProjects/transcrypt_hello/__javascript__/hello.min.js

[WinError 2] The system cannot find the file specifiedTraceback (most recent call last):
  File "c:\users\username\transcrypt_hello_virtualenv\lib\site-packages\transcrypt\__main__.py", line 99, in main
    compiler.Program (compilerPath, __symbols__)
  File "c:/users/username/transcrypt_hello_virtualenv/lib/site-packages/transcrypt/modules\org\transcrypt\compiler.py", line 223, in __init__
    minify.run (self.targetPath, self.miniTargetPath, self.shrinkMap.mapPath if utils.commandArgs.map else None, 6)     # Minifier has to accept JavaScript 6 input co
de, it is there in the autotest, even if not executed.
  File "c:/users/username/transcrypt_hello_virtualenv/lib/site-packages/transcrypt/modules\org\transcrypt\minify\__init__.py", line 25, in run
    subprocess.run (params)
  File "C:\Program Files (x86)\Python35-32\Lib\subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files (x86)\Python35-32\Lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Python35-32\Lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified


Aborted
```

**Comment by JdeH** [comment]
Hi,

I am not completely sure what the cause is, but probably the Google Closure minifier doesn't run at all.
It requires the Java Runtime Engine to be installed (which should have been in the docs but I think it isn't, so I'll add it).

You can check this by opening a command prompt and typing:

`java`

It should come up with a list of options.
If it doesn't, download and install the JRE for all users from e.g.: [http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html](http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html)

Let me know if this works for you.

Jacques

**Comment by nueverest** [comment]
Minification works after installing the JRE.

Thank you.

**Comment by JdeH** [comment]
Fine!

**Comment by nueverest** [comment]
I still like the idea of adding it to the docs as it not clear that the JRE is necessary.

**Comment by JdeH** [comment]
I will certainly add it

**Comment by JdeH** [comment]
I've seen it was already in the troubleshooting checklist of the installation paragraph.
But I've also added it to the requirements at the beginning of this paragraph, where it should be.

**Comment by nueverest** [comment]
Thanks.
