### ISSUE TITLE
transcrypt -h produces traceback

### ISSUE THREAD

**Issue by ceronman** [JdeH/Transcrypt#61]
When I run `transcrypt -h` I get the following error:

```
$ transcrypt -h
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.5.187
Copyright (C) Geatec Engineering. License: Apache 2.0

usage: transcrypt [-h] [-a] [-b] [-c] [-de] [-dm] [-dt] [-f] [-i] [-j] [-k]
                  [-l] [-m] [-n] [-o] [-p [PARENT]] [-r] [-t] [-v]
                  [source]

positional arguments:
  source                .py file containing source code of main module

optional arguments:
  -h, --help            show this help message and exit
  -a, --anno            annotate target files that were compiled from Python
                        with source file names and source line numbers
  -b, --build           rebuild all target files from scratch
  -c, --check           perform static check as part of compilation
  -de, --dextex         debug: show extended exception reports
  -dm, --dmap           debug: dump human readable source map
  -dt, --dtree          debug: dump syntax tree
  -f, --fcall           enable fastcall mechanism by default. You can also use
                        __pragma__ ('fcal') and __pragma__ ('nofcall')
  -i, --iconv           enable automatic conversion to iterable by default.
                        DISADVISED, since it will result in a type check for
                        each for-loop. Preferably use __pragma__ ('iconv') and
                        __pragma__ ('noiconv') to enable automatic conversion
                        locally
  -j, --jskeys          interpret {key: 'value'} as {'key': 'value'} and
                        forbid {key (): 'value'}, as JavaScript does.
                        DISADVISED, since it's less flexible than the Python
                        interpretation. Use {'key': 'value'} explicitly if you
                        want literal keys
  -k, --kwargs          enable keyword arguments by default. In general this
                        is DISADVISED, use __pragma__ ('kwargs') and
                        __pragma__('nokwargs') locally instead to prevent
                        bloated code
  -l, --license         show license
  -m, --map             generate source map
  -n, --nomin           no minification
  -o, --opov            enable operator overloading by default. In general
                        this is DISADVISED, use __pragma__ ('opov') and
                        __pragma__('noopov') locally instead to prevent slow
                        code
  -p [PARENT], --parent [PARENT]
                        object that will hold module, default is window. Use
                        -p .none to generate orphan module, e.g. for use in
                        node.js. Use -p .user to generate module that has to
                        be explicitly initialized by calling <modulename> (),
                        e.g. after the full page has loaded
  -r, --run             run source file rather than compiling it
  -t, --tconv           enable automatic conversion to truth value by default.
                        DISADVISED, since it will result in a conversion for
                        each boolean. Preferably use __pragma__ ('tconv') and
                        __pragma__ ('notconv') to enable automatic conversion
                        locally
  -v, --verbose         show all messages
Traceback (most recent call last):
  File "/Users/mceron/virtualenv/rattly/bin/transcrypt", line 9, in <module>
    load_entry_point('Transcrypt==3.5.187', 'console_scripts', 'transcrypt')()
  File "/Users/mceron/virtualenv/rattly/lib/python3.5/site-packages/transcrypt/__main__.py", line 52, in main
    utils.commandArgs.parse ()
  File "/Users/mceron/virtualenv/rattly/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/utils.py", line 48, in parse
    self.__dict__.update (self.argParser.parse_args () .__dict__)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1726, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1758, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1964, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1904, in consume_optional
    take_action(action, args, option_string)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1832, in take_action
    action(self, namespace, argument_values, option_string)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1017, in __call__
    parser.exit()
  File "/Users/mceron/virtualenv/rattly/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/utils.py", line 22, in exit
    raise CommandArgsExit ()
org.transcrypt.utils.CommandArgsExit
```

**Comment by JdeH** [comment]
Hi,

Unfortunately I tested this with a local version, which turned out to behave quite differently from a pip installed one.

I corrected this and tested via pip installation on Windows and Linux. It should be allright now in v 3.5.188. 
Also the exitcodes should work properly, let me know if otherwise.

Jacques
